
export const shippingRates = [
    {
        branch: "طرابلس",
        destinations: [
            {
            city: "طرابلس",
            homeDelivery: 20,
            branchPickup: 0,
            time: "24 ساعة",
            female: 30,
            },
            {
            city: "ضواحي طرابلس",
            homeDelivery: 25.30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 35.40,
            },
            {
            city: "بني وليد",
            homeDelivery: 35,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "ترهونة",
            homeDelivery: 35,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "مسلاتة",
            homeDelivery: 35,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "الزاوية",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "صرمان",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "المطرد",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "صبراتة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "العجيلات",
            homeDelivery: 30,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "رقدالين",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "زلطن",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الجميل",
            homeDelivery: 40,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "بوكماش",
            homeDelivery: 40,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "زوارة",
            homeDelivery: 35,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "القره بولي",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "زليتن",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "الخمس",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "ورشفانه/ الساعدية",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "غريان",
            homeDelivery: 30,
            branchPickup: 0,
            time: "48 ساعة",
            female: 45,
            },
            {
            city: "الاصابعة",
            homeDelivery: 35,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "القواليش",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "ام الجرسان",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "ككلة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "يفرن",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "المشاشية",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "القلعة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الرياينة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الزنتان",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الرجبان",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الرحيبات",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "جادو",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "طمزين",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "الحرابة",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "شكشوك",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "الجوش",
            homeDelivery: 55,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "بدر",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "تيجي",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الحوامد",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "نالوت",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "وازن",
            homeDelivery: 60,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "مصراتة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "سرت",
            homeDelivery: 40,
            branchPickup: 0,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "بوقرين",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الجفرة",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "راس لانوف",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "قمينس",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "جالو",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "اوجلة",
            homeDelivery: 50,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "البريقة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "تازربو",
            homeDelivery: 50,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الكفرة",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "بنغازي",
            homeDelivery: 35,
            branchPickup: 20,
            time: "48-72 ساعة",
            female: 0,
            },
            {
            city: "الابيار",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "الابرق",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "المرج",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "البيضاء",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "شحات",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "درنة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "طبرق",
            homeDelivery: 50,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "القبة",
            homeDelivery: 50,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "سوسة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "72 ساعة",
            female: 0,
            },
            {
            city: "سبها",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "اوباري",
            homeDelivery: 50,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "براك الشاطئ",
            homeDelivery: 45,
            branchPickup: 0,
            time: "3-4 أيام",
            female: 0,
            },
            {
            city: "ام الارانب",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "وادي عتبة",
            homeDelivery: 60,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "قطرون",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "القريات",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "مرزق",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "غات",
            homeDelivery: 60,
            branchPickup: 0,
            time: "4-6 أيام",
            female: 0,
            },
            {
            city: "تراغن",
            homeDelivery: 55,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
        ],
        },
        {
        branch: "بنغازي",
        destinations: [
            {
            city: "طرابلس (لباب البيت)",
            homeDelivery: 30,
            branchPickup: 15,
            time: "2-4 أيام",
            female: 35,
            },
            {
            city: "مصراتة",
            homeDelivery: 30,
            branchPickup: 15,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "زليتن",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الخمس",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "القره بولي",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "قصر خيار",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الزاوية",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "صبراته",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "صرمان",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "العجيلات",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الجميل",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "زوارة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "زلطن",
            homeDelivery: 45,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "العزيزية",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "بنغازي",
            homeDelivery: 20,
            branchPickup: 0,
            time: "خلال 24 ساعة",
            female: 0,
            },
            {
            city: "طبرق",
            homeDelivery: 35,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "البيضاء",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "أجدابيا",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "شحات",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "الابيار",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "المرج",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "درنة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "سبها",
            homeDelivery: 40,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
            {
            city: "الكفرة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "4-6 أيام",
            female: 0,
            },
            {
            city: "غريان",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "ورشفانة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الاصابعة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "3-6 أيام",
            female: 0,
            },
            {
            city: "يفرن",
            homeDelivery: 55,
            branchPickup: 0,
            time: "4-8 أيام",
            female: 0,
            },
            {
            city: "نالوت",
            homeDelivery: 55,
            branchPickup: 0,
            time: "4-8 أيام",
            female: 0,
            },
            {
            city: "الزنتان",
            homeDelivery: 55,
            branchPickup: 0,
            time: "4-8 أيام",
            female: 0,
            },
            {
            city: "جادو",
            homeDelivery: 55,
            branchPickup: 0,
            time: "4-8 أيام",
            female: 0,
            },
            {
            city: "بن وليد",
            homeDelivery: 40,
            branchPickup: 0,
            time: "4-6 أيام",
            female: 0,
            },
            {
            city: "سرت",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "ترهونة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-6 أيام",
            female: 0,
            },
            {
            city: "الجفرة",
            homeDelivery: 50,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
        ],
        },
        {
        branch: "مصراتة",
        destinations: [
            {
            city: "طرابلس (لباب البيت)",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 30,
            },
            {
            city: "طرابلس (استلام مكتب)",
            homeDelivery: 20,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "مصراتة (توصيل داخلي)",
            homeDelivery: 20,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 25,
            },
            {
            city: "مصراتة (توصيل نسائي)",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 25,
            },
            {
            city: "زليتن",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "قصر خيار",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "القره بولي",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "قماطة",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "الخمس",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "الزاوية",
            homeDelivery: 35,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "صبراته",
            homeDelivery: 40,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "صرمان",
            homeDelivery: 40,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "الجميل",
            homeDelivery: 40,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "رقدالين",
            homeDelivery: 40,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "العجيلات",
            homeDelivery: 40,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "زوارة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "العزيزية",
            homeDelivery: 40,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "ورشفانة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "بنغازي (لباب البيت)",
            homeDelivery: 30,
            branchPickup: 0,
            time: "2-3 أيام",
            female: 0,
            },
            {
            city: "بنغازي (استلام المكتب)",
            homeDelivery: 20,
            branchPickup: 0,
            time: "2-3 أيام",
            female: 0,
            },
            {
            city: "طبرق",
            homeDelivery: 45,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "البيضاء",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "درنة",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "المرج",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "شحات",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الابيار",
            homeDelivery: 35,
            branchPickup: 0,
            time: "2-3 أيام",
            female: 0,
            },
            {
            city: "زلطن",
            homeDelivery: 50,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "القبة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-6 أيام",
            female: 0,
            },
            {
            city: "جالو",
            homeDelivery: 45,
            branchPickup: 0,
            time: "4-6 أيام",
            female: 0,
            },
            {
            city: "سبها",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الكفرة",
            homeDelivery: 50,
            branchPickup: 0,
            time: "4-6 أيام",
            female: 0,
            },
            {
            city: "غريان",
            homeDelivery: 40,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "الاصابعة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "1-3 أيام",
            female: 0,
            },
            {
            city: "يفرن",
            homeDelivery: 50,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "نالوت",
            homeDelivery: 50,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "الزنتان",
            homeDelivery: 50,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "جادو",
            homeDelivery: 50,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "بن وليد",
            homeDelivery: 30,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "سرت",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "غات",
            homeDelivery: 50,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
            {
            city: "الجفرة",
            homeDelivery: 50,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
        ],
        },
        {
        branch: "غريان",
        destinations: [
            {
            city: "طرابلس (استلام مكتب)",
            homeDelivery: 20,
            branchPickup: 0,
            time: "24 ساعة",
            female: 0,
            },
            {
            city: "طرابلس (لباب البيت)",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24 ساعة",
            female: 35,
            },
            {
            city: "ضواحي طرابلس ",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24 ساعة",
            female: 35,
            },
            {
            city: "مصراتة (لباب البيت)",
            homeDelivery: 35,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 40,
            },
            {
            city: "مصراتة (استلام مكتب)",
            homeDelivery: 20,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "زليتن",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "الخمس",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "القره بوللي",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "قصر خيار",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "القويعة",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "قماطة",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "الزاوية",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "المطرد",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "صبراته",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "صرمان",
            homeDelivery: 30,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "الجميل",
            homeDelivery: 35,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "رقدالين",
            homeDelivery: 40,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "زوارة",
            homeDelivery: 35,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "العزيزية",
            homeDelivery: 20,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "قصر بن غشير",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "بنغازي (لباب البيت)",
            homeDelivery: 40,
            branchPickup: 0,
            time: "2-3 أيام",
            female: 0,
            },
            {
            city: "بنغازي (استلام مكتب)",
            homeDelivery: 25,
            branchPickup: 0,
            time: "2-3 أيام",
            female: 0,
            },
            {
            city: "الابيار",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "أجدابيا",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "جالو",
            homeDelivery: 50,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
            {
            city: "أوجلة",
            homeDelivery: 50,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
            {
            city: "المرج",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الابرق",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "القبة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "سوسة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "راس لانوف",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "البريقة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "طبرق",
            homeDelivery: 45,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "البيضاء",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "زلطن",
            homeDelivery: 40,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "شحات",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "درنة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "العجيلات",
            homeDelivery: 35,
            branchPickup: 0,
            time: "24-48 ساعة",
            female: 0,
            },
            {
            city: "سبها",
            homeDelivery: 35,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
            {
            city: "براك الشاطي",
            homeDelivery: 40,
            branchPickup: 0,
            time: "5-7 أيام",
            female: 0,
            },
            {
            city: "الكفرة",
            homeDelivery: 45,
            branchPickup: 0,
            time: "7-9 أيام",
            female: 0,
            },
            {
            city: "غريان (داخلي)",
            homeDelivery: 15,
            branchPickup: 0,
            time: "24 ساعة",
            female: 0,
            },
            {
            city: "مزدة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "ورشفانة",
            homeDelivery: 25,
            branchPickup: 0,
            time: "24-72 ساعة",
            female: 0,
            },
            {
            city: "الاصابعة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "يفرن",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "نالوت",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الزنتان",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "رجبان",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "القلعة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "الرابطة",
            homeDelivery: 25,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "القواليش",
            homeDelivery: 25,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "ككلة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "بئر غنم",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "بن وليد",
            homeDelivery: 30,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "مسلاتة",
            homeDelivery: 35,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "ترهونة",
            homeDelivery: 30,
            branchPickup: 0,
            time: "2-4 أيام",
            female: 0,
            },
            {
            city: "سرت",
            homeDelivery: 35,
            branchPickup: 0,
            time: "3-5 أيام",
            female: 0,
            },
            {
            city: "اوباري",
            homeDelivery: 45,
            branchPickup: 0,
            time: "7-10 أيام",
            female: 0,
            },
            {
            city: "الجفرة",
            homeDelivery: 40,
            branchPickup: 0,
            time: "7-9 أيام",
            female: 0,
            },
        ],
        },
    ];