export const deliveryData = [
    {
        branch: "طرابلس",
        destinations: [
        { city: "طرابلس (لباب البيت)", homeDelivery: 15, branchPickup: 0, time: "24 ساعة" , female: 20 },
        { city: "ضواحي طرابلس", homeDelivery: 20, branchPickup: 0, time: "24 ساعة" ,female:25},
        { city: "مصراتة", homeDelivery: 25, branchPickup: 15, time: "24-48 ساعة" ,female: 30},
        { city: "بنغازي", homeDelivery: 30, branchPickup: 15, time: "2-3 أيام" ,female: 0 },
        { city: "زليتن", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة" ,female: 0},
        { city: "الخمس", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة",female: 0 },
        { city: "القره بوللي", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة" ,female: 0},
        { city: "قصر خيار", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة" ,female: 0},
        { city: "الزاوية", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة",female: 0 },
        { city: "صبراتة", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة",female: 0 },
        { city: "صرمان", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة" ,female: 0},
        { city: "العجيلات", homeDelivery: 30, branchPickup: 0, time: "24-48 ساعة" ,female: 0},
        { city: "زوارة", homeDelivery: 30, branchPickup: 0, time: "24-48 ساعة" ,female: 0},
        { city: "غريان", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة",female: 0 },
        { city: "ترهونة", homeDelivery: 25, branchPickup: 0, time: "2-4 أيام",female: 0 },
        { city: "بني وليد", homeDelivery: 25, branchPickup: 0, time: "2-4 أيام",female: 0 },
        { city: "سبها", homeDelivery: 30, branchPickup: 0, time: "5-7 أيام",female: 0 },
        { city: "طبرق", homeDelivery: 40, branchPickup: 0, time: "3-5 أيام",female: 0 },
        { city: "البيضاء", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام",female: 0 },
        { city: "درنة", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام",female: 0 },
        { city: "الكفرة", homeDelivery: 40, branchPickup: 0, time: "7-9 أيام",female: 0 },
        { city: "القويعة", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "قماطة", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "المطرد", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "الجميل", homeDelivery: 30, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "رقدالين", homeDelivery: 35, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "العزيزية", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "قصر بن غشير", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "ورشفانة", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "جالو", homeDelivery: 45, branchPickup: 0, time: "3-6 أيام", female: 0 },
        { city: "أوجلة", homeDelivery: 45, branchPickup: 0, time: "3-6 أيام", female: 0 },
        { city: "الابرق", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة", female: 0 },
        { city: "القبة", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة", female: 0 },
        { city: "سوسة", homeDelivery: 35, branchPickup: 0, time: "24-72 ساعة", female: 0 },
        { city: "راس لانوف", homeDelivery: 35, branchPickup: 0, time: "48-120 ساعة", female: 0 },
        { city: "البريقة", homeDelivery: 35, branchPickup: 0, time: "48-120 ساعة", female: 0 },
        { city: "زلطن", homeDelivery: 35, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "رجبان", homeDelivery: 40, branchPickup: 0, time: "24-96 ساعة", female: 0 },
        { city: "القلعة", homeDelivery: 35, branchPickup: 0, time: "24-96 ساعة", female: 0 },
        { city: "الرابطة", homeDelivery: 30, branchPickup: 0, time: "24-96 ساعة", female: 0 },
        { city: "القواليش", homeDelivery: 35, branchPickup: 0, time: "24-120 ساعة", female: 0 },
        { city: "ككلة", homeDelivery: 35, branchPickup: 0, time: "24-120 ساعة", female: 0 },
        { city: "بئر غنم", homeDelivery: 40, branchPickup: 0, time: "24-120 ساعة", female: 0 },
        { city: "مسلاتة", homeDelivery: 30, branchPickup: 0, time: "24-72 ساعة", female: 0 },
        { city: "اوباري", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "الشوريف", homeDelivery: 35, branchPickup: 0, time: "24-72 ساعة", female: 0 },
        { city: "القريات", homeDelivery: 35, branchPickup: 0, time: "24-72 ساعة", female: 0 },
        { city: "ام الارنب", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "وادي عتبة", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "مرزق", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "تراغن", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "القطرون", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "غات", homeDelivery: 45, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "العوينات", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "الجفرة", homeDelivery: 35, branchPickup: 0, time: "3-6 أيام", female: 0 },
        ]
    },
    {
        branch: "بنغازي",
        destinations: [
        { city: "طرابلس (لباب البيت)", homeDelivery: 30, branchPickup: 0, time: "48-96 ساعة" , female: 30},
        { city: "طرابلس (استلام مكتب)", homeDelivery: 15, branchPickup: 0, time: "48-96 ساعة" ,female:0},
        { city: "مصراتة (لباب البيت)", homeDelivery: 30, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "مصراتة (استلام مكتب)", homeDelivery: 15, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "زليتن", homeDelivery: 25, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "الخمس", homeDelivery: 25, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "القره بولي", homeDelivery: 25, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "قصر خيار", homeDelivery: 25, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "الزاوية", homeDelivery: 30, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "صبراته", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "صرمان", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "العجيلات", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "الجميل", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "زوارة", homeDelivery: 40, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "زلطن", homeDelivery: 40, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "العزيزية", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة" ,female:0},
        { city: "بنغازي (داخلي)", homeDelivery: 15, branchPickup: 0, time: "24 ساعة",female:0 },
        { city: "طبرق", homeDelivery: 30, branchPickup: 0, time: "24-72 ساعة" ,female:0},
        { city: "البيضاء", homeDelivery: 25, branchPickup: 0, time: "24-72 ساعة",female:0 },
        { city: "أجدابيا", homeDelivery: 20, branchPickup: 0, time: "24-72 ساعة",female:0 },
        { city: "شحات", homeDelivery: 25, branchPickup: 0, time: "24-72 ساعة",female:0 },
        { city: "الابيار", homeDelivery: 25, branchPickup: 0, time: "24-72 ساعة",female:0 },
        { city: "المرج", homeDelivery: 25, branchPickup: 0, time: "24-72 ساعة",female:0 },
        { city: "درنة", homeDelivery: 25, branchPickup: 0, time: "24-72 ساعة",female:0 },
        { city: "سبها", homeDelivery: 35, branchPickup: 0, time: "72-120 ساعة",female:0 },
        { city: "الكفرة", homeDelivery: 40, branchPickup: 0, time: "72-120 ساعة" ,female:0},
        { city: "غريان", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "ورشفانة", homeDelivery: 35, branchPickup: 0, time: "48-73 ساعة",female:0 },
        { city: "الاصابعة", homeDelivery: 40, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "يفرن", homeDelivery: 50, branchPickup: 0, time: "72-120 ساعة",female:0 },
        { city: "نالوت", homeDelivery: 50, branchPickup: 0, time: "72-120 ساعة",female:0 },
        { city: "الزنتان", homeDelivery: 50, branchPickup: 0, time: "72-120 ساعة",female:0 },
        { city: "جادو", homeDelivery: 50, branchPickup: 0, time: "72-120 ساعة",female:0 },
        { city: "بن وليد", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "سرت", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "ترهونة", homeDelivery: 35, branchPickup: 0, time: "48-96 ساعة",female:0 },
        { city: "الجفرة", homeDelivery: 45, branchPickup: 0, time: "3-6 أيام",female:0 },
        ]
    },
    {
        branch: "مصراتة",
        destinations: [
        { city: "طرابلس (لباب البيت)", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 25 },
        { city: "طرابلس (استلام مكتب)", homeDelivery: 15, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "طرابلس (توصيل نسائي)", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 25 },
        { city: "مصراتة (توصيل داخلي)", homeDelivery: 15, branchPickup: 0, time: "24-48 ساعة", female: 20 },
        { city: "مصراتة (توصيل نسائي)", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 20 },
        { city: "زليتن", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "قصر خيار", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "القره بولي", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "قماطة", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "الخمس", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "الزاوية", homeDelivery: 30, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "صبراته", homeDelivery: 35, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "صرمان", homeDelivery: 35, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "الجميل", homeDelivery: 35, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "رقدالين", homeDelivery: 35, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "العجيلات", homeDelivery: 35, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "زوارة", homeDelivery: 40, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "العزيزية", homeDelivery: 35, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "ورشفانة", homeDelivery: 35, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "بنغازي (لباب البيت)", homeDelivery: 25, branchPickup: 0, time: "2-3 أيام", female: 0 },
        { city: "بنغازي (استلام المكتب)", homeDelivery: 15, branchPickup: 0, time: "2-3 أيام", female: 0 },
        { city: "طبرق", homeDelivery: 40, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "البيضاء", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "درنة", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "المرج", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "شحات", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "الابيار", homeDelivery: 30, branchPickup: 0, time: "2-3 أيام", female: 0 },
        { city: "زلطن", homeDelivery: 45, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "القبة", homeDelivery: 35, branchPickup: 0, time: "3-6 أيام", female: 0 },
        { city: "جالو", homeDelivery: 40, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "سبها", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "الكفرة", homeDelivery: 45, branchPickup: 0, time: "4-6 أيام", female: 0 },
        { city: "غريان", homeDelivery: 35, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "الاصابعة", homeDelivery: 40, branchPickup: 0, time: "1-3 أيام", female: 0 },
        { city: "يفرن", homeDelivery: 45, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "نالوت", homeDelivery: 45, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "الزنتان", homeDelivery: 45, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "جادو", homeDelivery: 45, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "بن وليد", homeDelivery: 25, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "سرت", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "غات", homeDelivery: 45, branchPickup: 0, time: "5-7 أيام", female: 0 },
        { city: "الجفرة", homeDelivery: 45, branchPickup: 0, time: "5-7 أيام", female: 0 },
        ]
    },
    {
        branch: "غريان",
        destinations: [
        { city: "طرابلس (استلام مكتب)", homeDelivery: 15, branchPickup: 0, time: "24 ساعة", female: 0 },
        { city: "طرابلس (لباب البيت)", homeDelivery: 25, branchPickup: 0, time: "24 ساعة", female: 30 },
        { city: "ضواحي طرابلس ", homeDelivery: 25, branchPickup: 0, time: "24 ساعة", female: 30 },
        { city: "مصراتة (لباب البيت)", homeDelivery: 30, branchPickup: 0, time: "24-48 ساعة", female: 35 },
        { city: "مصراتة (توصيل نسائي)", homeDelivery: 35, branchPickup: 0, time: "24-48 ساعة", female: 35 },
        { city: "مصراتة (استلام مكتب)", homeDelivery: 15, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "زليتن", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "الخمس", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "القره بوللي", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "قصر خيار", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "القويعة", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "قماطة", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "الزاوية", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "المطرد", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "صبراته", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "صرمان", homeDelivery: 25, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "الجميل", homeDelivery: 30, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "رقدالين", homeDelivery: 35, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "زوارة", homeDelivery: 30, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "العزيزية", homeDelivery: 15, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "قصر بن غشير", homeDelivery: 20, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "بنغازي (لباب البيت)", homeDelivery: 35, branchPickup: 0, time: "2-3 أيام", female: 0 },
        { city: "بنغازي (استلام مكتب)", homeDelivery: 20, branchPickup: 0, time: "2-3 أيام", female: 0 },
        { city: "الابيار", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "أجدابيا", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "جالو", homeDelivery: 45, branchPickup: 0, time: "5-7 أيام", female: 0 },
        { city: "أوجلة", homeDelivery: 45, branchPickup: 0, time: "5-7 أيام", female: 0 },
        { city: "المرج", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "الابرق", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "القبة", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "سوسة", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "راس لانوف", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "البريقة", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "طبرق", homeDelivery: 40, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "البيضاء", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "زلطن", homeDelivery: 35, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "شحات", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "درنة", homeDelivery: 35, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "العجيلات", homeDelivery: 30, branchPickup: 0, time: "24-48 ساعة", female: 0 },
        { city: "سبها", homeDelivery: 30, branchPickup: 0, time: "5-7 أيام", female: 0 },
        { city: "براك الشاطي", homeDelivery: 35, branchPickup: 0, time: "5-7 أيام", female: 0 },
        { city: "الكفرة", homeDelivery: 40, branchPickup: 0, time: "7-9 أيام", female: 0 },
        { city: "غريان (داخلي)", homeDelivery: 10, branchPickup: 0, time: "24 ساعة", female: 0 },
        { city: "مزدة", homeDelivery: 25, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "ورشفانة", homeDelivery: 20, branchPickup: 0, time: "24-72 ساعة", female: 0 },
        { city: "الاصابعة", homeDelivery: 25, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "يفرن", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "نالوت", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "الزنتان", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "رجبان", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "القلعة", homeDelivery: 25, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "الرابطة", homeDelivery: 20, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "القواليش", homeDelivery: 20, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "ككلة", homeDelivery: 25, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "بئر غنم", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "بن وليد", homeDelivery: 25, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "مسلاتة", homeDelivery: 30, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "ترهونة", homeDelivery: 25, branchPickup: 0, time: "2-4 أيام", female: 0 },
        { city: "سرت", homeDelivery: 30, branchPickup: 0, time: "3-5 أيام", female: 0 },
        { city: "اوباري", homeDelivery: 40, branchPickup: 0, time: "7-10 أيام", female: 0 },
        { city: "الجفرة", homeDelivery: 35, branchPickup: 0, time: "7-9 أيام", female: 0 },
        ]
    }
];